name: "linear_regression_model"
backend: "pytorch"
platform: "pytorch_libtorch"

input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 1 , 1]
  }
]

output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ 1 , 1]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]